services:
  db:
    restart: always
    build:
      context: ./tables-db/
      dockerfile: Dockerfile
    container_name: random_tables_db
    ports:
      - 3210:3210
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
